### ISSUE TITLE
Startzeitumwandlungsproblem

### ISSUE THREAD

**Issue by Twintips** [FranzHuebner/BAassist#49]
schönes Wort als Titel und genauer: in meinem WI Stundenplan will es den String " ITM" in eine Startzeit umwandeln. Wo genau das her kommt kann ich nicht sagen. Der Debugger muss da viele Schritte durchlaufen. 
Hier mal gleich meine Lösung. Ganz einfach den Returnwert 0 setzen, wenn da etwas schief läuft in convertTimeStringToInteger Methode. Ob es euch genügt, die Anforderung erfüllt und ob ihr es übernehmt müsst ihr entscheiden.

private int convertTimeStringToInteger(String input){
        String begOfLesson = input.substring(input.indexOf(":")+1);

        try{

            return Integer.parseInt(begOfLesson);
        }catch (NumberFormatException e){
            return 0;
        }
    }

Grüße gehen raus an Micha, danke für das Erwähnen der App:D

**Comment by Twintips** [comment]
Egal funktioniert nicht. Beim Fach wurde ein Komma eingetragen. Das zerhaut das ganze

**Comment by FranzHuebner** [comment]
Hey, Problem haben wir verstanden, kannst du uns mal einen String  zur Verfügung stellen? 
Wird ein Fach mit Komma getrennt also ×, xxx..  Oder werden 2 Fächer in einem durch SAP eingetragen also x, y?

**Comment by Twintips** [comment]
Also in der Gesamtheit sieht es so aus: 
{title: "KLAUSUR 08:00-09:00, ITM", start: 1528350300, end: 1528355700, allDay: false,…}

Also im String des Fachs("title") befindet sich ein Komma.

**Comment by RichyWalter** [comment]
Habe mich dem Problem angenommen und mit neuem json Parser behoben. Die Module mit Komma sollten jetzt auch korrekt angezeigt werden. Vielen Dank fürs Feedback
